{
 "title": "Terracotta",
 "description": "Sample dashboard for Terracotta(10.x) metrics exposed in Prometheus format.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cache", "label": "Cache", "query": { "query": "label_values(cache)" } },
   { "name": "cache_manager", "label": "Cache Manager", "query": { "query": "label_values(cache_manager)" } },
   { "name": "caching_client", "label": "Caching Client", "query": { "query": "label_values(client)" } },
   { "name": "dataset_manager", "label": "Dataset Manager", "query": { "query": "label_values(dataset_manager)" } },
   { "name": "dataset", "label": "Dataset", "query": { "query": "label_values(dataset)" } },
   { "name": "dataset_instance", "label": "Dataset Instance", "query": { "query": "label_values(dataset_instance)" } },
   { "name": "store_client", "label": "Store Client", "query": { "query": "label_values(client)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "TMC Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "FRS Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_tc_server_restartable_store_total_usage_bytes",
     "legendFormat": "{{server}} {{alias}}"
    }
   ]
  },
  {
   "title": "Offheap Allocated Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sag_tc_server_offheap_allocated_memory_bytes"
    }
   ]
  },
  {
   "title": "Dataset Main Record Occupied Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sag_tc_server_dataset_main_record_occupied_storage_bytes",
     "legendFormat": "{{alias}}-{{server}}"
    }
   ]
  },
  {
   "title": "Caching Store Data Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sag_tc_server_caching_store_data_size_bytes",
     "legendFormat": "{{alias}}-{{server}}"
    }
   ]
  },
  { "title": "Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Cache Hit Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sag_tc_cache_get_hit_latency_100_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "100 percentile"
    },
    {
     "expr": "sag_tc_cache_get_hit_latency_99_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sag_tc_cache_get_hit_latency_95_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "95 percentile"
    }
   ]
  },
  {
   "title": "Cache Miss Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sag_tc_cache_get_miss_latency_100_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "100 percentile"
    },
    {
     "expr": "sag_tc_cache_get_miss_latency_99_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sag_tc_cache_get_miss_latency_95_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "95 percentile"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(sag_tc_cache_hit_count_total[1m])",
     "legendFormat": "{{cache}}-{{cache_manager}} ({{client}})"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(sag_tc_cache_hit_count_total[1m]) / (rate(sag_tc_cache_hit_count_total[1m]) + rate(sag_tc_cache_miss_count_total[1m])))",
     "legendFormat": "{{cache}}-{{cache_manager}} ({{client}})"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(sag_tc_cache_miss_count_total[1m])",
     "legendFormat": "{{cache}}-{{cache_manager}} ({{client}})"
    }
   ]
  },
  {
   "title": "Cache Miss Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(sag_tc_cache_miss_count_total[1m]) / (rate(sag_tc_cache_hit_count_total[1m]) + rate(sag_tc_cache_miss_count_total[1m])))",
     "legendFormat": "{{cache}}-{{cache_manager}} ({{client}})"
    }
   ]
  },
  {
   "title": "Cache Put Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sag_tc_cache_put_latency_100_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "100 percentile"
    },
    {
     "expr": "sag_tc_cache_put_latency_99_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sag_tc_cache_put_latency_95_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "95 percentile"
    }
   ]
  },
  {
   "title": "Cache Remove Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sag_tc_cache_remove_latency_100_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "100 percentile"
    },
    {
     "expr": "sag_tc_cache_remove_latency_99_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sag_tc_cache_remove_latency_95_percentile{cache=\"$cache\", cache_manager=\"$cache_manager\", client=\"$caching_client\"}",
     "legendFormat": "95 percentile"
    }
   ]
  },
  { "title": "Store Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Dataset Add Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sag_tc_dataset_add_success_total[1m])",
     "legendFormat": "{{dataset}}-{{dataset_instance}}-{{dataset_manager}}"
    }
   ]
  },
  {
   "title": "Dataset Add Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sag_tc_dataset_add_latency_100_percentile{dataset=\"$dataset\", dataset_instance=\"$dataset_instance\", dataset_manager=\"$dataset_manager\", client=\"$store_client\"}",
     "legendFormat": "100 percentile"
    },
    {
     "expr": "sag_tc_dataset_add_latency_99_percentile{dataset=\"$dataset\", dataset_instance=\"$dataset_instance\", dataset_manager=\"$dataset_manager\", client=\"$store_client\"}",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sag_tc_dataset_add_latency_95_percentile{dataset=\"$dataset\", dataset_instance=\"$dataset_instance\", dataset_manager=\"$dataset_manager\", client=\"$store_client\"}",
     "legendFormat": "95 percentile"
    }
   ]
  },
  {
   "title": "Dataset Get Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sag_tc_dataset_get_success_total[1m])",
     "legendFormat": "{{dataset}}-{{dataset_instance}}-{{dataset_manager}}"
    }
   ]
  },
  {
   "title": "Dataset Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sag_tc_dataset_get_latency_100_percentile{dataset=\"$dataset\", dataset_instance=\"$dataset_instance\", dataset_manager=\"$dataset_manager\", client=\"$store_client\"}",
     "legendFormat": "100 percentile"
    },
    {
     "expr": "sag_tc_dataset_get_latency_99_percentile{dataset=\"$dataset\", dataset_instance=\"$dataset_instance\", dataset_manager=\"$dataset_manager\", client=\"$store_client\"}",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sag_tc_dataset_get_latency_95_percentile{dataset=\"$dataset\", dataset_instance=\"$dataset_instance\", dataset_manager=\"$dataset_manager\", client=\"$store_client\"}",
     "legendFormat": "95 percentile"
    }
   ]
  }
 ]
}